server:
  port: 8081


eureka:
  client:
    #表示将自己注册进EurekaServer 默认为true
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息,默认为true.单节点无所谓,集群必须为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      #设置与Eureka server交互的地址查询服务和注册服务都需要依赖这个地址
      defaultZone: http://localhost:7001/eureka/
      #集群部署
#      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/

spring:
  application:
    name: provider-kafka 
  cloud:
    stream:
      kafka:
        binder:
          brokers: 47.101.181.89:9092
          auto-create-topics: true
          zk-nodes: 8.129.88.114:2181
#      binders: 
      bindings: 
#        output:
#          destination: stream-demo
#          content-type: text/plain #发送消息的格式,接收端不用指定格式,但是发送端要
        greetings-in:
          destination: greetings
          contentType: application/json
        greetings-out: 
          destination: greetings
          contetnType: application/json

