server:
  port: 9527
  
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由的功能,利用微服务进行路由
      routes: 
        - id: payment_routh #payment_route    #路由的id,没有固定规则但要求唯一,建议配合f服务名
#          uri: http://localhost:8001          #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service      #匹配后提供服务的路由地址 (spring cloud netflix ribbon 会在定义lb前缀的m目标uri上实现负载均衡(官方文档))
          predicates:
            - Path=/payment/get/**            #断言,路径匹配进行路由
            
        - id: payment_routh2  #payment_rote     
#          uri: http://localhost:8001  
          uri: lb://cloud-payment-service  
          predicates:
            - Path=/payment/lb/**

eureka:
  client:
    service-url: 
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    hostname: cloud-gateway-service